# Generated by Django 4.0.5 on 2022-06-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendslist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
