# Generated by Django 4.0.5 on 2022-06-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_rename_users_chatusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.chatroom'),
        ),
    ]
