# Generated by Django 4.0.5 on 2022-06-25 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprelation',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
    ]
