# Generated by Django 4.0.5 on 2022-06-25 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0004_alter_friendshiprelation_friend_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshiprelation',
            unique_together={('user', 'friend')},
        ),
    ]
