# Generated by Django 4.0.5 on 2022-06-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_chatusers_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatusers',
            old_name='chat',
            new_name='chatroom',
        ),
    ]
