# Generated by Django 4.0.5 on 2022-06-26 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0005_rename_chat_chatusers_chatroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatUsers',
            new_name='ChatRoomUsers',
        ),
    ]
