# Generated by Django 4.0.5 on 2022-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_alter_friendshiprelation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshiprelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendshiprelation',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friendrelation'),
        ),
    ]
