# Generated by Django 4.0.5 on 2022-06-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_rename_chatusers_chatroomusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomusers',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat_app.chatroom'),
        ),
    ]
