# Generated by Django 4.0.5 on 2022-06-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_chatroomusers_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='chat_name',
            new_name='name',
        ),
    ]
