# Generated by Django 4.0.5 on 2022-06-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_rename_chat_name_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
